<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all()->keyBy('slug');

        $products = [
            ['category' => 'lego-city', 'name' => 'Міська Поліцейська Дільниця', 'slug' => 'city-police-station', 'price' => 3499, 'old_price' => 3999, 'stock' => 12, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 668, 'series' => 'City', 'country' => 'DK', 'description' => 'Велика дільниця з камерами, гаражем та службовими авто.', 'is_featured' => true, 'popularity' => 240],
            ['category' => 'lego-city', 'name' => 'Пожежна Станція 5+', 'slug' => 'city-fire-station', 'price' => 2899, 'old_price' => null, 'stock' => 18, 'age' => 5, 'difficulty' => 'easy', 'pieces' => 540, 'series' => 'City', 'country' => 'DK', 'description' => 'Пожежне депо з машинами та підйомним краном.', 'is_featured' => true, 'popularity' => 210],
            ['category' => 'lego-city', 'name' => 'Швидкісна Поліція з Переслідуванням', 'slug' => 'city-police-chase', 'price' => 1599, 'old_price' => 1899, 'stock' => 22, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 295, 'series' => 'City', 'country' => 'PL', 'description' => 'Перегони з поліцейським авто і швидким злодієм.', 'is_featured' => false, 'popularity' => 130],
            ['category' => 'lego-city', 'name' => 'Міський Потяг Express', 'slug' => 'city-express-train', 'price' => 4999, 'old_price' => null, 'stock' => 10, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 764, 'series' => 'City', 'country' => 'CZ', 'description' => 'Електропотяг із рейками та станцією.', 'is_featured' => true, 'popularity' => 260],
            ['category' => 'lego-city', 'name' => 'Будівельний Кран', 'slug' => 'city-construction-crane', 'price' => 2799, 'old_price' => null, 'stock' => 9, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 811, 'series' => 'City', 'country' => 'HU', 'description' => 'Висотний кран і будмайданчик з технікою.', 'is_featured' => false, 'popularity' => 140],
            ['category' => 'lego-city', 'name' => 'Полярна Станція Досліджень', 'slug' => 'city-arctic-station', 'price' => 3799, 'old_price' => 4199, 'stock' => 7, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 815, 'series' => 'City', 'country' => 'DK', 'description' => 'Експедиція на край світу з технікою та снігоходами.', 'is_featured' => false, 'popularity' => 155],

            ['category' => 'lego-star-wars', 'name' => 'X-Wing Зоряний Винищувач', 'slug' => 'x-wing-starfighter', 'price' => 5499, 'old_price' => null, 'stock' => 8, 'age' => 9, 'difficulty' => 'hard', 'pieces' => 1066, 'series' => 'Star Wars', 'country' => 'CZ', 'description' => 'Легендарний винищувач із детальною кабіною.', 'is_featured' => true, 'popularity' => 320],
            ['category' => 'lego-star-wars', 'name' => 'TIE Fighter', 'slug' => 'tie-fighter', 'price' => 2899, 'old_price' => 3199, 'stock' => 11, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 432, 'series' => 'Star Wars', 'country' => 'DK', 'description' => 'Класичний TIE зі стійками та пілотом.', 'is_featured' => false, 'popularity' => 180],
            ['category' => 'lego-star-wars', 'name' => 'Мандалорський Зореліт', 'slug' => 'mandalorian-ship', 'price' => 6299, 'old_price' => null, 'stock' => 6, 'age' => 10, 'difficulty' => 'hard', 'pieces' => 1183, 'series' => 'Star Wars', 'country' => 'PL', 'description' => 'Корабель із відсіками та міньфігурками.', 'is_featured' => true, 'popularity' => 280],
            ['category' => 'lego-star-wars', 'name' => 'Шолом Дарта Вейдера', 'slug' => 'vader-helmet', 'price' => 2499, 'old_price' => null, 'stock' => 15, 'age' => 18, 'difficulty' => 'medium', 'pieces' => 834, 'series' => 'Star Wars', 'country' => 'HU', 'description' => 'Колекційний шолом для фанатів саги.', 'is_featured' => false, 'popularity' => 205],
            ['category' => 'lego-star-wars', 'name' => 'Бойовий Набір 501', 'slug' => '501-battle-pack', 'price' => 1299, 'old_price' => 1499, 'stock' => 30, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 285, 'series' => 'Star Wars', 'country' => 'DK', 'description' => 'Солдати, техніка та аксесуари для битв.', 'is_featured' => false, 'popularity' => 190],
            ['category' => 'lego-star-wars', 'name' => 'AT-AT', 'slug' => 'atat-walker', 'price' => 9999, 'old_price' => null, 'stock' => 4, 'age' => 10, 'difficulty' => 'hard', 'pieces' => 1267, 'series' => 'Star Wars', 'country' => 'CZ', 'description' => 'Великий крокуючий AT-AT з рухомими ногами.', 'is_featured' => true, 'popularity' => 400],

            ['category' => 'lego-technic', 'name' => 'Technic Bugatti Chiron', 'slug' => 'technic-bugatti', 'price' => 12999, 'old_price' => null, 'stock' => 5, 'age' => 16, 'difficulty' => 'hard', 'pieces' => 3599, 'series' => 'Technic', 'country' => 'HU', 'description' => 'Суперкар з коробкою передач і підвіскою.', 'is_featured' => true, 'popularity' => 360],
            ['category' => 'lego-technic', 'name' => 'Technic Lamborghini Sián', 'slug' => 'technic-lamborghini', 'price' => 13499, 'old_price' => 14999, 'stock' => 3, 'age' => 18, 'difficulty' => 'hard', 'pieces' => 3696, 'series' => 'Technic', 'country' => 'DK', 'description' => 'Колекційний суперкар з відкривними дверима.', 'is_featured' => true, 'popularity' => 390],
            ['category' => 'lego-technic', 'name' => 'Всюдихід 4x4', 'slug' => 'technic-4x4', 'price' => 2999, 'old_price' => null, 'stock' => 16, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 723, 'series' => 'Technic', 'country' => 'PL', 'description' => 'Потужний всюдихід з підвіскою та лебідкою.', 'is_featured' => false, 'popularity' => 170],
            ['category' => 'lego-technic', 'name' => 'Пожежний Літак', 'slug' => 'technic-fire-plane', 'price' => 2199, 'old_price' => 2499, 'stock' => 12, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 478, 'series' => 'Technic', 'country' => 'CZ', 'description' => 'Літак з рухомими пропелерами та шасі.', 'is_featured' => false, 'popularity' => 145],
            ['category' => 'lego-technic', 'name' => 'Мотоцикл Ducati Panigale', 'slug' => 'technic-ducati', 'price' => 2499, 'old_price' => null, 'stock' => 9, 'age' => 10, 'difficulty' => 'medium', 'pieces' => 646, 'series' => 'Technic', 'country' => 'DK', 'description' => 'Деталізований спортбайк з підвіскою.', 'is_featured' => false, 'popularity' => 155],
            ['category' => 'lego-technic', 'name' => 'Карʼєрний Самоскид', 'slug' => 'technic-dump-truck', 'price' => 1599, 'old_price' => null, 'stock' => 20, 'age' => 7, 'difficulty' => 'easy', 'pieces' => 377, 'series' => 'Technic', 'country' => 'PL', 'description' => 'Самоскид з рухомим кузовом для вантажів.', 'is_featured' => false, 'popularity' => 120],

            ['category' => 'lego-friends', 'name' => 'Кафе в Хартлейк Сіті', 'slug' => 'friends-heartlake-cafe', 'price' => 2299, 'old_price' => null, 'stock' => 14, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 426, 'series' => 'Friends', 'country' => 'PL', 'description' => 'Затишне кафе з міні-ляльками та аксесуарами.', 'is_featured' => false, 'popularity' => 110],
            ['category' => 'lego-friends', 'name' => 'Ветеринарна Клініка', 'slug' => 'friends-vet-clinic', 'price' => 2599, 'old_price' => 2899, 'stock' => 10, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 617, 'series' => 'Friends', 'country' => 'DK', 'description' => 'Клініка для тваринок з каретою швидкої.', 'is_featured' => true, 'popularity' => 190],
            ['category' => 'lego-friends', 'name' => 'Будинок Дружби', 'slug' => 'friends-friendship-house', 'price' => 4199, 'old_price' => null, 'stock' => 8, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 1114, 'series' => 'Friends', 'country' => 'HU', 'description' => 'Великий будинок з кімнатами та басейном.', 'is_featured' => true, 'popularity' => 230],
            ['category' => 'lego-friends', 'name' => 'Автобус Пригод', 'slug' => 'friends-adventure-bus', 'price' => 2899, 'old_price' => null, 'stock' => 11, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 778, 'series' => 'Friends', 'country' => 'CZ', 'description' => 'Подорожній автобус із наметом і багаттям.', 'is_featured' => false, 'popularity' => 165],
            ['category' => 'lego-friends', 'name' => 'Магазин Солодощів', 'slug' => 'friends-candy-shop', 'price' => 1699, 'old_price' => 1999, 'stock' => 16, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 292, 'series' => 'Friends', 'country' => 'PL', 'description' => 'Солодощі, каса та міні-ляльки.', 'is_featured' => false, 'popularity' => 130],
            ['category' => 'lego-friends', 'name' => 'Рятувальний Вертоліт', 'slug' => 'friends-rescue-heli', 'price' => 2399, 'old_price' => null, 'stock' => 9, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 517, 'series' => 'Friends', 'country' => 'DK', 'description' => 'Порятунок на пляжі з вертольотом.', 'is_featured' => false, 'popularity' => 150],

            ['category' => 'lego-creator', 'name' => 'Creator 3-в-1 Модульний Будинок', 'slug' => 'creator-modular-house', 'price' => 3699, 'old_price' => null, 'stock' => 7, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 1261, 'series' => 'Creator', 'country' => 'DK', 'description' => 'Три варіанти будинку в одному наборі.', 'is_featured' => true, 'popularity' => 220],
            ['category' => 'lego-creator', 'name' => 'Creator Тигр 3-в-1', 'slug' => 'creator-tiger', 'price' => 1599, 'old_price' => null, 'stock' => 13, 'age' => 7, 'difficulty' => 'easy', 'pieces' => 755, 'series' => 'Creator', 'country' => 'PL', 'description' => 'Тигр, папуга або риба — збирай і змінюй.', 'is_featured' => false, 'popularity' => 140],
            ['category' => 'lego-creator', 'name' => 'Creator Космічний Ровер', 'slug' => 'creator-space-rover', 'price' => 1199, 'old_price' => 1399, 'stock' => 20, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 311, 'series' => 'Creator', 'country' => 'CZ', 'description' => 'Космічний ровер з міні-роботом.', 'is_featured' => false, 'popularity' => 125],
            ['category' => 'lego-creator', 'name' => 'Creator Ретро Мотоцикл', 'slug' => 'creator-retro-bike', 'price' => 999, 'old_price' => null, 'stock' => 25, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 230, 'series' => 'Creator', 'country' => 'DK', 'description' => 'Класичний мотоцикл у стилі ретро.', 'is_featured' => false, 'popularity' => 95],
            ['category' => 'lego-creator', 'name' => 'Creator Вежа з Левом', 'slug' => 'creator-lion-tower', 'price' => 2699, 'old_price' => null, 'stock' => 8, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 1426, 'series' => 'Creator', 'country' => 'HU', 'description' => 'Фортеця з левом для рольових ігор.', 'is_featured' => true, 'popularity' => 205],
            ['category' => 'lego-creator', 'name' => 'Creator Сучасний Будинок', 'slug' => 'creator-modern-house', 'price' => 2999, 'old_price' => 3299, 'stock' => 9, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 939, 'series' => 'Creator', 'country' => 'PL', 'description' => 'Стильний будинок з басейном та інтер’єром.', 'is_featured' => false, 'popularity' => 160],

            ['category' => 'lego-ninjago', 'name' => 'Ninjago Дракон Справедливості', 'slug' => 'ninjago-justice-dragon', 'price' => 3499, 'old_price' => null, 'stock' => 10, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 739, 'series' => 'Ninjago', 'country' => 'DK', 'description' => 'Дракон з рухомими крилами та ніндзя.', 'is_featured' => true, 'popularity' => 240],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Мех Ллойда', 'slug' => 'ninjago-lloyd-mech', 'price' => 2199, 'old_price' => null, 'stock' => 15, 'age' => 7, 'difficulty' => 'easy', 'pieces' => 544, 'series' => 'Ninjago', 'country' => 'PL', 'description' => 'Великий мех зі зброєю та ніндзя.', 'is_featured' => false, 'popularity' => 170],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Літак Блискавка', 'slug' => 'ninjago-thunder-jet', 'price' => 2999, 'old_price' => 3399, 'stock' => 7, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 833, 'series' => 'Ninjago', 'country' => 'CZ', 'description' => 'Швидкісний літак з катапультами.', 'is_featured' => true, 'popularity' => 210],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Храм Дракона', 'slug' => 'ninjago-dragon-temple', 'price' => 4899, 'old_price' => null, 'stock' => 6, 'age' => 9, 'difficulty' => 'hard', 'pieces' => 1212, 'series' => 'Ninjago', 'country' => 'DK', 'description' => 'Храм з пастками, драконами та ніндзя.', 'is_featured' => true, 'popularity' => 260],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Спінер Кая', 'slug' => 'ninjago-kai-spinner', 'price' => 699, 'old_price' => null, 'stock' => 40, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 56, 'series' => 'Ninjago', 'country' => 'PL', 'description' => 'Швидкі бої зі спінером Кая.', 'is_featured' => false, 'popularity' => 110],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Вогняний Робот', 'slug' => 'ninjago-fire-mech', 'price' => 3199, 'old_price' => null, 'stock' => 9, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 984, 'series' => 'Ninjago', 'country' => 'HU', 'description' => 'Мех з підсвіткою та бойовими модулями.', 'is_featured' => false, 'popularity' => 175],

            ['category' => 'lego-city', 'name' => 'Рятувальний Гелікоптер', 'slug' => 'city-rescue-helicopter', 'price' => 1399, 'old_price' => null, 'stock' => 21, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 215, 'series' => 'City', 'country' => 'PL', 'description' => 'Гелікоптер з лебідкою та рятувальником.', 'is_featured' => false, 'popularity' => 105],
            ['category' => 'lego-city', 'name' => 'Швидка Допомога', 'slug' => 'city-ambulance', 'price' => 1199, 'old_price' => null, 'stock' => 19, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 184, 'series' => 'City', 'country' => 'DK', 'description' => 'Машина швидкої допомоги з обладнанням.', 'is_featured' => false, 'popularity' => 98],

            ['category' => 'lego-creator', 'name' => 'Creator Морський Круїз', 'slug' => 'creator-cruise-ship', 'price' => 3499, 'old_price' => 3899, 'stock' => 6, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 962, 'series' => 'Creator', 'country' => 'DK', 'description' => 'Круїзний лайнер з палубою та каютами.', 'is_featured' => false, 'popularity' => 175],
            ['category' => 'lego-technic', 'name' => 'Підйомний Кран Heavy Duty', 'slug' => 'technic-heavy-crane', 'price' => 6999, 'old_price' => null, 'stock' => 4, 'age' => 11, 'difficulty' => 'hard', 'pieces' => 2171, 'series' => 'Technic', 'country' => 'DK', 'description' => 'Потужний кран з підйомною стрілою.', 'is_featured' => true, 'popularity' => 300],
            ['category' => 'lego-star-wars', 'name' => 'База Повстанців', 'slug' => 'rebel-base', 'price' => 4599, 'old_price' => null, 'stock' => 7, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 1047, 'series' => 'Star Wars', 'country' => 'PL', 'description' => 'База з ангаром та командним центром.', 'is_featured' => false, 'popularity' => 190],
            ['category' => 'lego-friends', 'name' => 'Готель для Тварин', 'slug' => 'friends-pet-hotel', 'price' => 1999, 'old_price' => 2199, 'stock' => 12, 'age' => 7, 'difficulty' => 'easy', 'pieces' => 418, 'series' => 'Friends', 'country' => 'CZ', 'description' => 'Готель з кімнатами для улюбленців.', 'is_featured' => false, 'popularity' => 135],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Сітка Небезпеки', 'slug' => 'ninjago-danger-net', 'price' => 1499, 'old_price' => null, 'stock' => 17, 'age' => 7, 'difficulty' => 'easy', 'pieces' => 315, 'series' => 'Ninjago', 'country' => 'PL', 'description' => 'Арена для битв зі зброєю та пастками.', 'is_featured' => false, 'popularity' => 120],
            ['category' => 'lego-creator', 'name' => 'Creator Космічний Шатл', 'slug' => 'creator-space-shuttle', 'price' => 1899, 'old_price' => null, 'stock' => 14, 'age' => 7, 'difficulty' => 'easy', 'pieces' => 310, 'series' => 'Creator', 'country' => 'DK', 'description' => 'Шатл з відсіком для вантажу.', 'is_featured' => false, 'popularity' => 115],
            ['category' => 'lego-city', 'name' => 'Міський Аеропорт', 'slug' => 'city-airport', 'price' => 5999, 'old_price' => 6499, 'stock' => 5, 'age' => 8, 'difficulty' => 'hard', 'pieces' => 1382, 'series' => 'City', 'country' => 'DK', 'description' => 'Аеропорт з літаком, терміналом і технікою.', 'is_featured' => true, 'popularity' => 280],
            ['category' => 'lego-star-wars', 'name' => 'Броньований Транспорт', 'slug' => 'armored-transport', 'price' => 3999, 'old_price' => null, 'stock' => 9, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 852, 'series' => 'Star Wars', 'country' => 'CZ', 'description' => 'Бронетранспорт з озброєнням і фігурками.', 'is_featured' => false, 'popularity' => 175],
            ['category' => 'lego-technic', 'name' => 'Экскаватор Гусеничний', 'slug' => 'technic-excavator', 'price' => 3299, 'old_price' => null, 'stock' => 9, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 569, 'series' => 'Technic', 'country' => 'HU', 'description' => 'Гусеничний екскаватор з рухомим ковшем.', 'is_featured' => false, 'popularity' => 150],
            ['category' => 'lego-friends', 'name' => 'Пляжний Рятувальний Центр', 'slug' => 'friends-beach-rescue', 'price' => 2399, 'old_price' => null, 'stock' => 10, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 512, 'series' => 'Friends', 'country' => 'PL', 'description' => 'Рятувальна станція з човном і квадроциклом.', 'is_featured' => false, 'popularity' => 145],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Бойовий Мотоцикл', 'slug' => 'ninjago-battle-bike', 'price' => 1299, 'old_price' => null, 'stock' => 18, 'age' => 7, 'difficulty' => 'easy', 'pieces' => 262, 'series' => 'Ninjago', 'country' => 'DK', 'description' => 'Мотоцикл з шипами та зброєю ніндзя.', 'is_featured' => false, 'popularity' => 125],
            ['category' => 'lego-creator', 'name' => 'Creator Містечко', 'slug' => 'creator-townhouse', 'price' => 2499, 'old_price' => null, 'stock' => 11, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 939, 'series' => 'Creator', 'country' => 'CZ', 'description' => 'Містечковий будинок з магазином на першому поверсі.', 'is_featured' => false, 'popularity' => 150],
            ['category' => 'lego-city', 'name' => 'Поліцейський Гелікоптер', 'slug' => 'city-police-heli', 'price' => 1499, 'old_price' => 1699, 'stock' => 14, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 267, 'series' => 'City', 'country' => 'DK', 'description' => 'Поліцейський гелікоптер з прожектором.', 'is_featured' => false, 'popularity' => 110],
            ['category' => 'lego-star-wars', 'name' => 'Рейдерський Шатл', 'slug' => 'raider-shuttle', 'price' => 4299, 'old_price' => null, 'stock' => 6, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 1060, 'series' => 'Star Wars', 'country' => 'DK', 'description' => 'Шатл з турелями та десантним відсіком.', 'is_featured' => false, 'popularity' => 185],
            ['category' => 'lego-technic', 'name' => 'Вертоліт Рятувальник', 'slug' => 'technic-rescue-heli', 'price' => 1799, 'old_price' => null, 'stock' => 12, 'age' => 8, 'difficulty' => 'easy', 'pieces' => 200, 'series' => 'Technic', 'country' => 'PL', 'description' => 'Вертоліт з лебідкою для рятування.', 'is_featured' => false, 'popularity' => 120],
            ['category' => 'lego-friends', 'name' => 'Еко Будиночок', 'slug' => 'friends-eco-house', 'price' => 3799, 'old_price' => null, 'stock' => 8, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 1143, 'series' => 'Friends', 'country' => 'DK', 'description' => 'Еко-будинок з сонячними панелями.', 'is_featured' => true, 'popularity' => 210],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Гонка на Драконах', 'slug' => 'ninjago-dragon-race', 'price' => 2699, 'old_price' => null, 'stock' => 9, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 764, 'series' => 'Ninjago', 'country' => 'HU', 'description' => 'Два дракони та арена для змагань.', 'is_featured' => false, 'popularity' => 165],
            ['category' => 'lego-city', 'name' => 'Міська Лікарня', 'slug' => 'city-hospital', 'price' => 4299, 'old_price' => null, 'stock' => 8, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 816, 'series' => 'City', 'country' => 'DK', 'description' => 'Сучасна лікарня з каретою швидкої.', 'is_featured' => true, 'popularity' => 230],
            ['category' => 'lego-city', 'name' => 'Поліцейська Академія', 'slug' => 'city-police-academy', 'price' => 3199, 'old_price' => null, 'stock' => 10, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 823, 'series' => 'City', 'country' => 'PL', 'description' => 'Тренування, траси та службовий транспорт.', 'is_featured' => false, 'popularity' => 180],
            ['category' => 'lego-technic', 'name' => 'Technic McLaren Formula', 'slug' => 'technic-mclaren', 'price' => 7999, 'old_price' => 8599, 'stock' => 5, 'age' => 18, 'difficulty' => 'hard', 'pieces' => 1432, 'series' => 'Technic', 'country' => 'DK', 'description' => 'Колекційний болід із деталізацією.', 'is_featured' => true, 'popularity' => 320],
            ['category' => 'lego-technic', 'name' => 'Technic Volvo Навантажувач', 'slug' => 'technic-volvo-loader', 'price' => 6799, 'old_price' => null, 'stock' => 6, 'age' => 11, 'difficulty' => 'hard', 'pieces' => 2193, 'series' => 'Technic', 'country' => 'SE', 'description' => 'Велика техніка з рухомими механізмами.', 'is_featured' => false, 'popularity' => 210],
            ['category' => 'lego-star-wars', 'name' => 'Millennium Falcon', 'slug' => 'millennium-falcon', 'price' => 8999, 'old_price' => null, 'stock' => 4, 'age' => 9, 'difficulty' => 'hard', 'pieces' => 1351, 'series' => 'Star Wars', 'country' => 'DK', 'description' => 'Легендарний корабель із деталями та мініфігурками.', 'is_featured' => true, 'popularity' => 420],
            ['category' => 'lego-star-wars', 'name' => 'Imperial Star Destroyer', 'slug' => 'imperial-destroyer', 'price' => 9999, 'old_price' => null, 'stock' => 3, 'age' => 10, 'difficulty' => 'hard', 'pieces' => 1555, 'series' => 'Star Wars', 'country' => 'DK', 'description' => 'Великий корабель Імперії для колекції.', 'is_featured' => false, 'popularity' => 280],
            ['category' => 'lego-friends', 'name' => 'Friends Магазин Тварин', 'slug' => 'friends-pet-shop', 'price' => 1899, 'old_price' => null, 'stock' => 14, 'age' => 6, 'difficulty' => 'easy', 'pieces' => 388, 'series' => 'Friends', 'country' => 'PL', 'description' => 'Магазин із тваринками та аксесуарами.', 'is_featured' => false, 'popularity' => 125],
            ['category' => 'lego-friends', 'name' => 'Friends Школа', 'slug' => 'friends-school', 'price' => 3299, 'old_price' => null, 'stock' => 9, 'age' => 7, 'difficulty' => 'medium', 'pieces' => 766, 'series' => 'Friends', 'country' => 'HU', 'description' => 'Школа з класами та спортмайданчиком.', 'is_featured' => false, 'popularity' => 160],
            ['category' => 'lego-creator', 'name' => 'Creator Класичний Пікап', 'slug' => 'creator-pickup', 'price' => 2099, 'old_price' => null, 'stock' => 12, 'age' => 8, 'difficulty' => 'medium', 'pieces' => 858, 'series' => 'Creator', 'country' => 'DK', 'description' => 'Класичний пікап у стилі ретро.', 'is_featured' => false, 'popularity' => 135],
            ['category' => 'lego-ninjago', 'name' => 'Ninjago Титан Мех', 'slug' => 'ninjago-titan-mech', 'price' => 3499, 'old_price' => null, 'stock' => 8, 'age' => 9, 'difficulty' => 'medium', 'pieces' => 840, 'series' => 'Ninjago', 'country' => 'DK', 'description' => 'Великий мех для епічних битв.', 'is_featured' => true, 'popularity' => 230],
        ];

        foreach ($products as $product) {
            $categoryId = $categories[$product['category']]->id ?? null;
            if (! $categoryId) {
                continue;
            }

            Product::query()->updateOrCreate(
                ['slug' => $product['slug']],
                [
                    'category_id' => $categoryId,
                    'name' => $product['name'],
                    'price' => $product['price'],
                    'old_price' => $product['old_price'],
                    'stock' => $product['stock'],
                    'age' => $product['age'],
                    'difficulty' => $product['difficulty'],
                    'pieces' => $product['pieces'],
                    'brand' => 'LEGO',
                    'series' => $product['series'],
                    'country' => $product['country'],
                    'description' => $product['description'],
                    'is_featured' => $product['is_featured'],
                    'is_active' => true,
                    'popularity' => $product['popularity'],
                    'created_at' => now()->subDays(rand(0, 35)),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
